### PR TITLE
Arduino ci

### PR DESCRIPTION
**Pull request by RobTillaart**

### CODE REVIEW

**Comment by RobTillaart** [comment]
@milesburton

I made an issue at - https://github.com/Arduino-CI/arduino_ci/issues/251 - to get the unit tests running. Got Stuck.
If I have done my libraries I might have a look at the Dallas Temperature library too. 
That also need to have that issue fixed.

What could be done is to have the example sketches compiled at each push/PR.
Better make an issue in your repo for this if you want this CI added.

**Comment by milesburton** [comment]
We've been lacking CI for far too long so even a start would be better than
nothing. I've never written unit tests for hardware level code so this is a
new world to me.

If you get time, that'd be great.

**Comment by RobTillaart** [comment]
I created an issue at your repo.

**Comment by milesburton** [comment]
Thanks Rob, let me take a look through in the morning. I appreciate your
time.

**Pull request merged**
